# Default values for stone-soup-pipelines.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

stoneSoupPipeline:
  subscription:
    install: true
  namespace: stone-soup-ci
  serviceAccount: pipeline

