apiVersion: v2
description: A Helm chart to configure Hashicorp's vault
keywords:
- pattern
name: hashicorp-vault
version: 0.0.4
dependencies:
  - name: vault
    version: "0.24.1"
    repository: "file://subcharts/vault/"
      # repository: "https://charts.hybrid-cloud-patterns.io/"
maintainers:
- email: claudiol@redhat.com
  name: claudiol
- email: michele@redhat.com
  name: michele
- email: kellinmcavoy@gmail.com
  name: mcavoyk
