apiVersion: v2
description: A Helm chart to configure the golang-based external-secrets
keywords:
- pattern
name: golang-external-secrets
version: 0.0.2
dependencies:
  - name: external-secrets
    version: "0.8.3"
    repository: "https://charts.external-secrets.io"
    # "https://external-secrets.github.io/kubernetes-external-secrets"
maintainers:
- email: claudiol@redhat.com
  name: claudiol
- email: michele@redhat.com
  name: michele
