---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: httpd-frontend
  managedFields:
  name: http-port
spec:
  port:
    targetPort: http-port
  to:
    kind: Service
    name: http-port
    weight: 100
