---
apiVersion: v1
kind: Service
metadata:
  name: https-port
  labels:
    app: httpd-frontend
spec:
  ports:
    - port: 8443
      name: https-port
      protocol: TCP
      targetPort: 8443
  selector:
    app: httpd-frontend
